---

- hosts: all
  become: true
  tasks:
          - name: update repository index
            apt:
                    update_cache: yes
            when: ansible_distribution in ["Ubuntu"]


          - name: install apache2 package
            apt:
                    name: apache2
                    state: latest
            when: ansible_distribution in ["Ubuntu"]

          - name: add php support for apache
            apt:
                    name: libapache2-mod-php
                    state: latest
            when: ansible_distribution in ["Ubuntu"]

          - name: update CentOS repository index
            dnf:
                    update_cache: yes
            when: ansible_distribution == "CentOS"


          - name: install httpd package in CentOS
            dnf:
                    name: httpd
                    state: latest
            when: ansible_distribution == "CentOS"

          - name: add php support for apache in CentOS
            dnf:
                    name: php
                    state: latest
            when: ansible_distribution == "CentOS"	
